security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    makaira:
                        password: '%env(API_PASSWORD)%' # see .env or environment variable


    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        api_secured:
            pattern: ^/api/
            stateless: true
            http_basic:
                realm: "API Authentication"
                provider: in_memory