stages:
  - deploy

deploy:
  variables:
    BASE_RELEASE_DIR: "/var/www/picture-similarity.makaira.cloud"
    RELEASE_DIR: "${BASE_RELEASE_DIR}/${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}-$(date +%Y%m%d%H%M%S)"
  stage: deploy
  script:
    - echo ${RELEASE_DIR}
