stages:
  - deploy

deploy:
  variables:
    BASE_RELEASE_DIR: "/var/www/releases/picture-similarity.makaira.cloud"
    RELEASE_DIR: "${BASE_RELEASE_DIR}/${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}"
    SYMLINK: "/var/www/picture-similarity.makaira.cloud"
  stage: deploy
  script:
    - test ! -d ${RELEASE_DIR}
    - composer install -no --no-dev
    - echo "DATABASE_URL=${DATABASE_URL}" >> .env.local
    - echo "APP_ENV=prod" >> .env.local
    - echo "APP_SECRET=${APP_SECRET}" >> .env.local
    - cat <(echo -e "AuthType Basic\nAuthName "'"'API'"'"\nAuthUserFile /var/www/picture-similarity.makaira.cloud/.htpasswd\nRequire valid-user\n") public/.htaccess > public/.htaccess
    - sudo mkdir -p ${RELEASE_DIR}
    - echo "Copy source to ${RELEASE_DIR}"
    - sudo rsync -auv --exclude-from=.rsync-exclude * .env .env.local .htpasswd ${RELEASE_DIR}
    - echo "Set owner and group of ${RELEASE_DIR}"
    - sudo chown -R www-data:www-data ${RELEASE_DIR}
    - echo "Symlink ${SYMLINK} to ${RELEASE_DIR}"
    - sudo ln -snf ${RELEASE_DIR} ${SYMLINK}
