services:
  app:
    build:
      context: .docker/api/
      args:
        BASE_IMAGE: php:8.5-apache-trixie
    volumes:
      - ".:/app"
    environment:
      PHP_IDE_CONFIG: serverName=${HOST:-picture-similarity.docker.localhost}
    labels:
      proxy.config: ${HOST:-picture-similarity.docker.localhost}:80
    networks:
      - default
      - proxy
    deploy:
      replicas: ${DEV_ENV:-1}

  db:
    image: mysql:8.4
    volumes:
      - "db:/var/lib/mysql"
      - ".docker/db/:/docker-entrypoint-initdb.d/:ro"
    environment:
      MYSQL_DATABASE: picture-similarity
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}

  app-test:
    build:
      context: .docker/api/
      args:
        BASE_IMAGE: php:8.5-cli-trixie
    command:
      - /app/bin/phpunit
    volumes:
      - ".:/app"
    environment:
      APP_ENV: test
      PHP_IDE_CONFIG: serverName=${HOST:-picture-similarity.docker.localhost}
    deploy:
      replicas: ${TEST_ENV:-0}

volumes:
  db:

networks:
  proxy:
    name: dev_proxy
    external: true
