#get_available_types:
#    methods: GET
#    path: /api/{shop}/available-types
#    controller: Makaira\PictureSimilarity\Controller\PictureSimilarityController:getAvailableTypes
#
#api:
#    methods: GET
#    path: /api/{shop}/{productId}
#    controller: Makaira\PictureSimilarity\Controller\PictureSimilarityController:find
#
#api_multiple_product_ids:
#    methods: GET
#    path: /api/{shop}/products/{productIds}
#    controller: Makaira\PictureSimilarity\Controller\PictureSimilarityController:findByProductIds
#
#type:
#    methods: GET
#    path: /api/{type}/{shop}/{productId}
#    controller: Makaira\PictureSimilarity\Controller\PictureSimilarityController:find
#
#type_multiple_product_ids:
#    methods: GET
#    path: /api/{type}/{shop}/products/{$productIdList}
#    controller: Makaira\PictureSimilarity\Controller\PictureSimilarityController:findByProductIds
