api:
    path: /api/{shop}/{productId}
    controller: App\Controller\PictureSimilarityController:find

type:
    path: /api/{type}/{shop}/{productId}
    controller: App\Controller\PictureSimilarityController:find
