[date]
date.timezone = Europe/Berlin

[xdebug]
xdebug.discover_client_host = off
xdebug.client_host = "host.docker.internal"
xdebug.client_port = 9003
xdebug.start_with_request = "trigger"
xdebug.trigger_value = ""
xdebug.mode = "debug,develop"
xdebug.cli_color = On
xdebug.max_nesting_level = 512
xdebug.var_display_max_children = 256
xdebug.var_display_max_data = 1024
xdebug.var_display_max_depth = 10
